config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # /posts/1/comments/2
  resources :posts do
    resources :comments
  end
  get "inicio", controller: "home", action: "index", as: "home"

  # get "students", controller: "students", action: "index", as: "estudantes"
  
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_rich_text :body

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #quando o post for excluído, os comentários tbm serão
  has_many :comments, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
      @comment = @post.comments.create(comment_params)
      @comment.user = current_user

      if @comment.save
          flash[:notice] = "Comentário criado com sucesso"
          redirect_to post_path(@post)
      else
          flash[:alert] = "Comentário não foi criado"
          redirect_to post_path(@post)
      end
  end

  def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post)
  end

  def update
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
        if @comment.update(comment_params)
            format.html{redirect_to post_path(@post), notice: "Comentario atualizado"}
        else
            format.html{redirect_to post_path(@post), alert: "Erro na atualização"}

        end
    end
  end

  private

  def set_post
      @post = Post.find(params[:post_id])
  end

  def comment_params
      params.require(:comment).permit(:body)
  end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @author = "Rodrigo"
    @posts = [
      {title: "Rails", body: "Aprendendo com a OBC"},
      {title: "Pyton", body: "Aprendendo com a OBC"},
      {title: "Javascript", body: "Aprendendo com a OBC"}
    ]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = [
      {nome: "Revin", telefone: "6283672844"},
      {nome: "Pedro", telefone: "6283845992"},
      {nome: "Joao", telefone: "6283845992"},
      {nome: "Silveira", telefone: "6283845992"}

    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="card mb-4 shadow-sm border-0">
  <div class="card-header d-flex justify-content-between align-items-center bg-light border-bottom-0">
    <div class="d-flex align-items-center gap-2">
      <i class="bi bi-person-circle text-primary fs-4"></i>
      <div>
        <strong><%= comment.user.email %></strong>
        <% if (comment.updated_at - comment.created_at) > 1 %>
          <span class="text-muted ms-2 small">• Editado <%= time_ago_in_words(comment.updated_at) %> atrás</span>
        <% else %>
          <span class="text-muted ms-2 small">• Postado <%= time_ago_in_words(comment.created_at) %> atrás</span>
        <% end %>
      </div>
    </div>
    
      <% if current_user == comment.user %>
    <div class="btn-group gap-2">
      <%= link_to "#", remote: true, data: {
        controller: "comments",
        action: 'comments#toggleForm',
        comments_form_param: "edit-form-#{comment.id}",
        comments_body_param: "comment-body-#{comment.id}"
      }, class: "btn btn-outline-primary btn-sm", id: "edit-button-#{comment.id}" do %>
        <i class="bi bi-pencil-square me-1"></i> Editar
      <% end %>
      
      <%= button_to [post, comment], method: :delete, class: "btn btn-outline-danger btn-sm", data: { confirm: "Tem certeza que deseja excluir este comentário?" } do %>
        <i class="bi bi-trash3 me-1"></i> Excluir
      <% end %>
    </div>
  <% end %>

  </div>

  <!-- Formulário de Edição Oculto -->
  <div id="edit-form-<%= comment.id %>" class="d-none p-3 bg-body-tertiary rounded-3">
    <%= render "comments/form", post: post, comment: comment, submit_label: "Update" %>
  </div>

  <!-- Corpo do Comentário -->
  <div id="comment-body-<%= comment.id %>" class="card-body">
    <p class="card-text lh-lg"><%= comment.body %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], class: "mb-3") do |f| %>
  <div class="mb-3 mt-4">
    <%= f.label :body, "Your Comment", class: "form-label" %>
    <%= f.rich_text_area :body, rows: 5, class: "form-control", placeholder: "Write your comment here..." %>
  </div>
  <div>
    <%= f.submit submit_label, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Blog pessoal</h1>
<p>Para conferir meus posts, clique no botão a seguir</p>
<%= link_to "Blog", posts_path, class: "btn btn-primary" %>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!-- Brand -->
    <%= link_to "RailsBlog", root_path, class: "navbar-brand" %>
    
    <!-- Toggle Button -->
    <button 
      class="navbar-toggler" 
      type="button" 
      data-bs-toggle="collapse" 
      data-bs-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" 
      aria-expanded="false" 
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
      </ul>

      <!-- Dropdown -->
      <ul class="navbar-nav">
        <%= render "user/session" %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

  </head>

  <body class="">
    <header>
      <%= render "layouts/navbar"%>
      <%= render "layouts/alerts" %>
    </header>
    <div class="container mb-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "mt-4") do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class="card mb-3 mt-4">
  <div class="card-body">
    <h5 class="card-title">
      <strong>Title:</strong> <%= post.title %>
    </h5>
    
    <p class="card-text">
      <strong>Views:</strong> <%= pluralize(post.views, "view") %>
      <p>publicado por: <%= post.user.email %></p>
    </p>

    <p class="card-text">
      <strong>Body:</strong> <%= post.body %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<h1 class="mb-4 mt-4">Posts</h1>

<div id="posts" class="list-group">
  <% @posts.each do |post| %>
    <div class="list-group-item mb-2">
      <%= render post %>

      <p>
        <%= link_to "Show this post", post, class: "btn btn-primary btn-sm" %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New post", new_post_path, class: "btn btn-success mt-3" %>

app/views/posts/new.html.erb
<h1 class="mb-4 mt-4">New Post</h1>

<%= render "form", post: @post %>

<div class="mt-3">
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
</div>

app/views/posts/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<%= render @post %>
<div class="mt-4">
  <div class="btn-group gap-2" role="group">
    <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-warning btn-sm" %>
    <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-sm" %>
    <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this post?" } %>
  </div>

  <%= render "comments/form", post: @post, comment: @post.comments.build, submit_label: "Replay" %>

  <% @comments.each do |comment| %>
    <%= render "comments/comment", post: @post, comment: comment %>
  <% end%>
</div>

app/views/students/index.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Lista de Estudantes</h1>
  <hr class="mb-4">

  <div class="accordion" id="accordionEstudantes">
    <% @students.each_with_index do |item, index| %>
      <div class="accordion-item mb-2">
        <h2 class="accordion-header" id="heading<%= index %>">
          <button 
            class="accordion-button collapsed" 
            type="button" 
            data-bs-toggle="collapse" 
            data-bs-target="#collapse<%= index %>" 
            aria-expanded="false" 
            aria-controls="collapse<%= index %>">
            <i class="bi bi-person-circle me-2"></i> <%= item[:nome] %>
          </button>
        </h2>
        <div 
          id="collapse<%= index %>" 
          class="accordion-collapse collapse" 
          aria-labelledby="heading<%= index %>" 
          data-bs-parent="#accordionEstudantes">
          <div class="accordion-body">
            <p><strong>Telefone:</strong> <%= item[:telefone] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="mt-4 text-center">
    <%= link_to "Voltar para Home", home_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/user/_session.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a 
      class="nav-link dropdown-toggle" 
      href="#" 
      id="navbarDropdown" 
      role="button" 
      data-bs-toggle="dropdown" 
      aria-expanded="false"
    >
      Dropdown
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li class="nav-item">
        <%= link_to "Novo Post", new_post_path, class: "dropdown-item" %>
      </li>
      <li class="nav-item">
        <a class="dropdown-item" href="#">Action</a>
      </li>
      <li class="nav-item">
        <a class="dropdown-item" href="#">Another action</a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Cadastro", new_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  </li>
<% end %>